Cloudflare pages: try adding optional rollup dependency
I'm trying to deploy on Cloudflare pages, but the build fails with error:

```
Error: Cannot find module @rollup/rollup-linux-x64-gnu
```

The docs don't mention this is required:
- https://developers.cloudflare.com/pages/framework-guides/deploy-a-vite3-project/
- https://vite.dev/guide/static-deploy.html#cloudflare-pages

But this issue mentions it's required when building on Docker:
https://github.com/vitejs/vite/discussions/15532#discussioncomment-8527272